# Generated by Django 2.2.24 on 2021-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Bookmark'),
        ),
    ]
